version: '3.8'
services:
  web:
    build: .
    ports:
      - "3001:3001"
    environment:
      - PG_USER=$PG_USER
      - PG_PWD=$PG_PWD
      - PG_DB=$PG_DB
      - DATABASE_URI=postgresql://$PG_USER:$PG_PWD@db/$PG_DB
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    volumes:
      - /var/lib/postgresql/14/main:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PWD
      POSTGRES_DB: $PG_DB
    ports:
      - "5432:5432" 